WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Repositories/ShirtRepository.cs
namespace WebApp.Models.Repositories
{
    public static class ShirtRepository
    {
        private static List<Shirt> shirts = new List<Shirt>()
        {
            new Shirt { ShirtId = 2, Brand = "My Brand", Color = "Black", Gender = "Men", Price = 35, Size = 12 },
            new Shirt { ShirtId = 3, Brand = "Your Brand", Color = "Pink", Gender = "Women", Price = 28, Size = 8 },
            new Shirt { ShirtId = 4, Brand = "Your Brand", Color = "Yello", Gender = "Women", Price = 30, Size = 9 }
        };

        public static List<Shirt> GetShirts()
        {
            return shirts;
        }

        public static bool ShirtExists(int id)
        {
            return shirts.Any(x => x.ShirtId == id);
        }

        public static Shirt? GetShirtById(int id)
        {
            return shirts.FirstOrDefault(x => x.ShirtId == id);
        }

        public static Shirt? GetShirtByProperties(string? brand, string? gender, string? color, int? size)
        {
            return shirts.FirstOrDefault(x =>
                !string.IsNullOrWhiteSpace(brand) &&
                !string.IsNullOrWhiteSpace(x.Brand) &&
                x.Brand.Equals(brand, StringComparison.OrdinalIgnoreCase) &&
                !string.IsNullOrWhiteSpace(gender) &&
                !string.IsNullOrWhiteSpace(x.Gender) &&
                x.Gender.Equals(gender, StringComparison.OrdinalIgnoreCase) &&
                !string.IsNullOrWhiteSpace(color) &&
                !string.IsNullOrWhiteSpace(x.Color) &&
                x.Color.Equals(color, StringComparison.OrdinalIgnoreCase) &&
                size.HasValue &&
                x.Size.HasValue &&
                size.Value == x.Size.Value);
        }

        public static void AddShirt(Shirt shirt)
        {
            int maxId = shirts.Max(x => x.ShirtId);
            shirt.ShirtId = maxId + 1;

            shirts.Add(shirt);
        }

        public static void UpdateShirt(Shirt shirt)
        {
            var shirtToUpdate = shirts.First(x => x.ShirtId == shirt.ShirtId);
            shirtToUpdate.Brand = shirt.Brand;
            shirtToUpdate.Price = shirt.Price;
            shirtToUpdate.Size = shirt.Size;
            shirtToUpdate.Color = shirt.Color;
            shirtToUpdate.Gender = shirt.Gender;
        }

        public static void DeleteShirt(int shirtId)
        {
            var shirt = GetShirtById(shirtId);
            if (shirt != null)
            {
                shirts.Remove(shirt);
            }
        }
    }
}

WebApp/Models/Shirt.cs
using System.ComponentModel.DataAnnotations;
using WebApp.Models.Validations;

namespace WebApp.Models
{
    public class Shirt
    {
        public int ShirtId { get; set; }

        [Required]
        public string? Brand { get; set; }

        [Required]
        public string? Color { get; set; }

        [Shirt_EnsureCorrectSizing]
        public int? Size { get; set; }

        [Required]
        public string? Gender { get; set; }

        public double? Price { get; set; }
    }
}

WebApp/Models/Validations/Shirt_EnsureCorrectSizingAttribute.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models.Validations
{
    public class Shirt_EnsureCorrectSizingAttribute : ValidationAttribute
    {
        protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
        {
            var shirt = validationContext.ObjectInstance as Shirt;

            if (shirt != null && !string.IsNullOrWhiteSpace(shirt.Gender))
            {
                if (shirt.Gender.Equals("men", StringComparison.OrdinalIgnoreCase) && shirt.Size < 8)
                {
                    return new ValidationResult("For men's shirts, the size has to be greater or equal to 8.");
                }
                else if (shirt.Gender.Equals("women", StringComparison.OrdinalIgnoreCase) && shirt.Size < 6)
                {
                    return new ValidationResult("For women's shirts, the size has to be greater or equal to 6.");
                }
            }

            return ValidationResult.Success;
        }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/ShirtsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using WebApp.Data;
using WebApp.Models;
using WebApp.Models.Repositories;

namespace WebApp.Controllers
{
    public class ShirtsController : Controller
    {
        private readonly IWebApiExecuter webApiExecuter;

        public ShirtsController(IWebApiExecuter webApiExecuter)
        {
            this.webApiExecuter = webApiExecuter;
        }

        public async Task<IActionResult> Index()
        {
            return View(await webApiExecuter.InvokeGet<List<Shirt>>("shirts"));
        }

        public IActionResult CreateShirt()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateShirt(Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var response = await webApiExecuter.InvokePost("shirts", shirt);
                    if (response != null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (WebApiException ex)
                {
                    HandleWebApiException(ex);
                }

            }

            return View(shirt);
        }

        public async Task<IActionResult> UpdateShirt(int shirtId)
        {
            try
            {
                var shirt = await webApiExecuter.InvokeGet<Shirt>($"shirts/{shirtId}");
                if (shirt != null)
                {
                    return View(shirt);
                }
            }
            catch (WebApiException ex)
            {
                HandleWebApiException(ex);
                return View();
            }


            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateShirt(Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await webApiExecuter.InvokePut($"shirts/{shirt.ShirtId}", shirt);
                    return RedirectToAction(nameof(Index));
                }
                catch (WebApiException ex)
                {
                    HandleWebApiException(ex);
                }

            }

            return View(shirt);
        }

        public async Task<IActionResult> DeleteShirt(int shirtId)
        {
            try
            {
                await webApiExecuter.InvokeDelete($"shirts/{shirtId}");
                return RedirectToAction(nameof(Index));
            }
            catch (WebApiException ex)
            {
                HandleWebApiException(ex);
                return View(nameof(Index),
                    await webApiExecuter.InvokeGet<List<Shirt>>("shirts"));
            }
        }

        private void HandleWebApiException(WebApiException ex)
        {
            if (ex.ErrorResponse != null &&
                ex.ErrorResponse.Errors != null &&
                ex.ErrorResponse.Errors.Count > 0)
            {
                foreach (var error in ex.ErrorResponse.Errors)
                {
                    ModelState.AddModelError(error.Key, string.Join("; ", error.Value));
                }
            }
            else if (ex.ErrorResponse != null)
            {
                ModelState.AddModelError("Error", ex.ErrorResponse.Title);
            }
            else
            {
                ModelState.AddModelError("Error", ex.Message);
            }
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shirts" asp-action="Index">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shirts/CreateShirt.cshtml
@model Shirt

<h3>Shirt</h3>
<br />
<form method="post" asp-action="CreateShirt">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Brand" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Brand" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Brand"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Gender" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Gender" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Gender"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Color" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Color" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Color"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Size" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="number" asp-for="Size" class="form-control" min="1" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Size"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Price" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
        <div class="col-6">
        </div>
    </div>
</form>

WebApp/Views/Shirts/Index.cshtml
@model List<Shirt>

<div class="text-danger" asp-validation-summary="All"></div>

<h3>Shirts</h3>
<br />

@if (Model != null)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Brand</td>
                <td>Gender</td>
                <td>Color</td>
                <td>Size</td>
                <td>Price</td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var shirt in Model)
            {
                <tr>
                    <td>@shirt.Brand</td>
                    <td>@shirt.Gender</td>
                    <td>@shirt.Color</td>
                    <td>@shirt.Size</td>
                    <td>@(shirt.Price.HasValue ? shirt.Price.Value.ToString("c") : "")</td>
                    <td><a class="btn btn-link" asp-controller="shirts" asp-action="updateshirt" asp-route-shirtId="@shirt.ShirtId">Edit</a> </td>
                    <td><a class="btn btn-link" asp-controller="shirts" asp-action="deleteshirt" asp-route-shirtId="@shirt.ShirtId">Delete</a> </td>
                </tr>
            }
        </tbody>
    </table>
}

<br />
<a class="btn btn-primary" asp-controller="shirts" asp-action="createshirt">Create</a>

WebApp/Views/Shirts/UpdateShirt.cshtml
@model Shirt

<h3>Shirt</h3>
<br />
<form method="post" asp-action="UpdateShirt">
    <input type="hidden" asp-for="ShirtId" />
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Brand" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Brand" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Brand"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Gender" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Gender" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Gender"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Color" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="text" asp-for="Color" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Color"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Size" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="number" asp-for="Size" class="form-control" min="1" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Size"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <label asp-for="Price" class="col-form-label"></label>
        </div>
        <div class="col-6">
            <input type="number" asp-for="Price" class="form-control" />
        </div>
        <div class="col">
            <span class="text-danger" asp-validation-for="Price"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        <div class="col-6">
        </div>
    </div>
</form>